# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{testify}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{John Hyland}]
  s.date = %q{2011-10-31}
  s.email = %q{github@djspinmonkey.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/framework.rb",
    "lib/middleware.rb",
    "lib/runner.rb",
    "lib/test_result.rb",
    "lib/testify.rb",
    "samples/README",
    "samples/awesome_runner.rb",
    "samples/awesome_test_framework.rb",
    "samples/awesome_tests/asplode.aws",
    "samples/awesome_tests/failing.aws",
    "samples/awesome_tests/passing.aws",
    "samples/dots.rb",
    "samples/summary.rb",
    "spec/framework_spec.rb",
    "spec/middleware_spec.rb",
    "spec/runner_spec.rb",
    "spec/sample_framework.rb",
    "spec/sample_tests/failing_tests",
    "spec/sample_tests/mixed_tests",
    "spec/sample_tests/passing_tests",
    "spec/sample_tests/test_helper",
    "spec/spec_helper.rb",
    "spec/test_result_spec.rb",
    "spec/testify_spec.rb"
  ]
  s.homepage = %q{http://github.com/djspinmonkey/testify}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Testify is a test framework framework.  Think "Rack for testing."}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<classy>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<classy>, [">= 1.0.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<classy>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<classy>, [">= 1.0.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<classy>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<classy>, [">= 1.0.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

